version: 2.1

aliases:
  - &onlymaster
    filters:
      branches:
        only: master

jobs:
  deploy:
    docker:
      - image: circleci/node
    parameters:
      package_dir:
        type: string
      package_name:
        type: string
    steps:
      - checkout
      - run:
          name: Halt on no changes 
          working_directory: fbcnms-packages/<<parameters.package_dir>>
          command: |
            published=$(npm -s show <<parameters.package_name>> version)
            current=$(node -p "require('./package.json').version")
            if [[ $published == $current ]]; then
              circleci step halt
            fi
      - run:
          name: npn auth
          working_directory: fbcnms-packages/<<parameters.package_dir>>
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: npm publish
          working_directory: fbcnms-packages/<<parameters.package_dir>>
          command: npm publish --access public   

workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy:
          name: deploy-fbcnms-strings
          package_dir: fbcnms-strings
          package_name: fbcnms/strings
          <<: *onlymaster
      - deploy:
          name: deploy-fbcnms-util
          package_dir: fbcnms-util
          package_name: fbcnms/util
          <<: *onlymaster
