version: 2

aliases:
  - &onlymaster
    filters:
      branches:
        only: master

jobs:
  deploy:
    docker:
      - image: circleci/node
    parameters:
      package_dir:
        type: string
      package_name:
        type: string
    steps:
      - checkout
      - run:
          working_directory: project/fbcnms-packages/<<parameters.package_dir>>
          name: End step if version has not changed
          command: |
            published=$(npm -s show <<parameters.package_name>> version)
            current=$(node -p "require('./package.json').version")
            if [[ $published == $current ]]; then
              circleci step halt
            fi
      - run:
          name: Authenticate with registry
          working_directory: ~/project/fbcnms-packages/<<parameters.package_dir>>
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: npm publish
          working_directory: project/fbcnms-packages/<<parameters.package_dir>>
          command: npm publish --access public   
          
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          package_dir: fbcnms-strings
          package_name: fbcnms/strings
          <<: *onlymaster
