version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: cd ~/fbcnms-packages/fbcnms-auth && npm publish
          
          
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
